name: Build, Test, and Deploy to Maven Central

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - id: install-secret-key
      name: Install gpg secret key
      run: |
        # Install gpg secret key
        cat <(echo -e "${{ secrets.OSSRH_GPG_SECRET_KEY }}") | gpg --batch --import
    
    - uses: actions/checkout@v3
    
    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'
        
    - name: Gradle 'build'
      uses: gradle/gradle-build-action@v2
      with:
        arguments: build
    
    - name: Gradle 'release'
      uses: gradle/gradle-build-action@v2
      env:
        MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
        MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
        OSSRG_GPG_ID: ${{ secrets.OSSRG_GPG_ID }}
        OSSRH_GPG_SECRET_KEY_PASSWORD: ${{ secrets.OSSRH_GPG_SECRET_KEY_PASSWORD }}
      with:
        arguments: publish
